name: Build and Deploy - Dev

on: workflow_dispatch

jobs:
  build:
    uses: nhst/infra-common-github-actions/.github/workflows/node-workflow-template.yaml@dev
    with:
      node_version: "24.x"
      image_name: s3-storage-viewer
      ecr_repository: editorial
      namespace: editorial
      action_env: DEV
      upload_dist: "no"
      require_node_build: "no"                # the Docker image builds the app itself
      multi_repo: false
      package_manager: npm
    secrets: inherit
